SUCCESS_WITH_3_SLOTS = {
    "sessions": [
        {
            "center_id": 579419,
            "name": "St Johns Hospital",
            "address": "Sarjapura Road",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "09:00:00",
            "to": "12:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "43c3e397-983f-48a4-9118-1d424f9d72de",
            "date": "01-08-2021",
            "available_capacity": 132,
            "available_capacity_dose1": 91,
            "available_capacity_dose2": 41,
            "fee": "780",
            "min_age_limit": 45,
            "allow_all_age": False,
            "vaccine": "COVISHIELD",
            "slots": [],
        },
        {
            "center_id": 579419,
            "name": "St Johns Hospital",
            "address": "Sarjapura Road",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "09:00:00",
            "to": "12:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "9c00794a-5ad2-40ea-9a39-f578a1671218",
            "date": "01-08-2021",
            "available_capacity": 167,
            "available_capacity_dose1": 117,
            "available_capacity_dose2": 50,
            "fee": "780",
            "min_age_limit": 18,
            "max_age_limit": 44,
            "allow_all_age": False,
            "vaccine": "COVISHIELD",
            "slots": [
                "09:00AM-11:00AM",
            ],
        },
        {
            "center_id": 588210,
            "name": "MARVELL HOSPITAL",
            "address": "1ST BLOCK KORMANGALA",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "11:30:00",
            "to": "15:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "5c44fc1b-3c84-43b3-82be-45665861a3f3",
            "date": "01-08-2021",
            "available_capacity": 200,
            "available_capacity_dose1": 100,
            "available_capacity_dose2": 100,
            "fee": "780",
            "min_age_limit": 18,
            "allow_all_age": True,
            "vaccine": "COVISHIELD",
            "slots": ["11:30AM-01:30PM", "01:30PM-03:00PM"],
        },
    ]
}

SUCCESS_WITH_1_SLOT = {
    "sessions": [
        {
            "center_id": 579419,
            "name": "St Johns Hospital",
            "address": "Sarjapura Road",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "09:00:00",
            "to": "12:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "43c3e397-983f-48a4-9118-1d424f9d72de",
            "date": "01-08-2021",
            "available_capacity": 132,
            "available_capacity_dose1": 91,
            "available_capacity_dose2": 41,
            "fee": "780",
            "min_age_limit": 45,
            "allow_all_age": False,
            "vaccine": "COVISHIELD",
            "slots": [
                "09:00AM-11:00AM",
            ],
        },
        {
            "center_id": 579419,
            "name": "St Johns Hospital",
            "address": "Sarjapura Road",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "09:00:00",
            "to": "12:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "9c00794a-5ad2-40ea-9a39-f578a1671218",
            "date": "01-08-2021",
            "available_capacity": 167,
            "available_capacity_dose1": 117,
            "available_capacity_dose2": 50,
            "fee": "780",
            "min_age_limit": 18,
            "max_age_limit": 44,
            "allow_all_age": False,
            "vaccine": "COVISHIELD",
            "slots": [],
        },
        {
            "center_id": 588210,
            "name": "MARVELL HOSPITAL",
            "address": "1ST BLOCK KORMANGALA",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "11:30:00",
            "to": "15:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "5c44fc1b-3c84-43b3-82be-45665861a3f3",
            "date": "01-08-2021",
            "available_capacity": 200,
            "available_capacity_dose1": 100,
            "available_capacity_dose2": 100,
            "fee": "780",
            "min_age_limit": 18,
            "allow_all_age": True,
            "vaccine": "COVISHIELD",
            "slots": [],
        },
    ]
}

SUCCESS_WITH_NO_SLOT = {
    "sessions": [
        {
            "center_id": 579419,
            "name": "St Johns Hospital",
            "address": "Sarjapura Road",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "09:00:00",
            "to": "12:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "43c3e397-983f-48a4-9118-1d424f9d72de",
            "date": "01-08-2021",
            "available_capacity": 132,
            "available_capacity_dose1": 91,
            "available_capacity_dose2": 41,
            "fee": "780",
            "min_age_limit": 45,
            "allow_all_age": False,
            "vaccine": "COVISHIELD",
            "slots": [],
        },
        {
            "center_id": 579419,
            "name": "St Johns Hospital",
            "address": "Sarjapura Road",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "09:00:00",
            "to": "12:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "9c00794a-5ad2-40ea-9a39-f578a1671218",
            "date": "01-08-2021",
            "available_capacity": 167,
            "available_capacity_dose1": 117,
            "available_capacity_dose2": 50,
            "fee": "780",
            "min_age_limit": 18,
            "max_age_limit": 44,
            "allow_all_age": False,
            "vaccine": "COVISHIELD",
            "slots": [],
        },
        {
            "center_id": 588210,
            "name": "MARVELL HOSPITAL",
            "address": "1ST BLOCK KORMANGALA",
            "state_name": "Karnataka",
            "district_name": "BBMP",
            "block_name": "South",
            "pincode": 560034,
            "from": "11:30:00",
            "to": "15:00:00",
            "lat": 12,
            "long": 77,
            "fee_type": "Paid",
            "session_id": "5c44fc1b-3c84-43b3-82be-45665861a3f3",
            "date": "01-08-2021",
            "available_capacity": 200,
            "available_capacity_dose1": 100,
            "available_capacity_dose2": 100,
            "fee": "780",
            "min_age_limit": 18,
            "allow_all_age": True,
            "vaccine": "COVISHIELD",
            "slots": [],
        },
    ]
}
